config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
  }

  resources :brigade, only: %i[show edit] do
    post :add_leader, on: :member
  end

  resources :projects, only: %i[index] do
    get 'search', on: :collection
  end

  root to: 'home#show'
end

app/models/brigade.rb
class Brigade < ApplicationRecord
  extend FriendlyId
  include MetricSnapshottable

  has_many :brigade_leaders
  has_many :brigade_projects

  friendly_id :name, use: :slugged

  metric :meetup_past_rsvps, -> { meetup&.body&.fetch('past_rsvps', nil) }
  metric :meetup_repeat_rsvpers, -> { meetup&.body&.fetch('repeat_rsvpers', nil) }
  metric :meetup_past_events, -> { meetup&.body&.fetch('past_events', nil) }
  metric :meetup_member_count, -> { meetup&.body&.fetch('member_count', nil) }
  metric :meetup_upcoming_events, -> { meetup&.body&.fetch('upcoming_events', nil) }
  metric :meetup_organizer_count, -> { meetup&.body&.fetch('organizers', [])&.count }

  def self.replace_all_from_brigade_information(brigades)
    Brigade.transaction do
      official_brigades = brigades.map do |brigade|
        json = brigade.body
        is_official = json['tags'].include?('Code for America') && json['tags'].include?('Official')

        existing = Brigade.find_by(name: json['name'])
        new_attributes = {
          name: json['name'],
          meetup_url: (json['events_url'] if json['events_url'].try(:match, %r{\Ahttps?://www\.meetup\.com})),
          github_url: (json['projects_list_url'] if json['projects_list_url'].try(:match, %r{\Ahttps?://github\.com})),
        }.compact

        if !existing && is_official
          Brigade.create(new_attributes)
        elsif existing && !is_official
          # remove no-longer-official brigades
          existing.destroy
          nil
        elsif existing
          # propagate some useful attributes onto the Brigade model itself
          existing.meetup_url ||= new_attributes[:meetup_url]
          existing.github_url ||= new_attributes[:github_url]
          existing.save
          existing
        end
      end

      Brigade.where.not(id: official_brigades).destroy_all
    end
  end

  def meetup_urlname
    return unless meetup_url

    URI(meetup_url)
      .path
      .gsub(/^\/|\/$/, '') # "/Code-for-Foo/" => "Code-for-Foo"
  end

  def meetup
    return unless meetup_urlname

    @meetup ||= ApiObject::MeetupGroup.with_meetup_urlname(meetup_urlname).first
  end
end

app/controllers/brigade_controller.rb
class BrigadeController < ApplicationController
  before_action :set_brigade
  before_action :can_edit_brigade, only: %i[edit add_leader]

  def show
    @meetup_page = @brigade.meetup
    @projects = @brigade.brigade_projects.includes(:github_repo, :github_repo_details).order(last_pushed_at: :desc)
    @stats = @brigade.metric_snapshots
  end

  def edit
  end

  def add_leader
    new_brigade_leader = BrigadeLeader.create(
      brigade_leader_params.merge(
        brigade: @brigade
      )
    )

    if new_brigade_leader
      flash[:info] = 'Successfully added Brigade Leader'
    else
      flash[:error] = 'Error adding Brigade leader'
    end

    redirect_to edit_brigade_path(@brigade)
  end

  private

  def set_brigade
    @brigade = Brigade.friendly.find(params.fetch(:id, params[:brigade_id]))
  end

  def can_edit_brigade
    return redirect_to root_url unless current_user.present?

    unless current_user.can_manage_brigade?(@brigade)
      return redirect_to root_url, flash: { error: "You don't have permission to edit this Brigade." }
    end
  end

  def brigade_leader_params
    params
      .fetch(:brigade_leader, {})
      .permit(:name, :email)
  end
end

app/views/brigade/edit.html.haml
.container
  .row
    .col-12
      %h1 Edit #{@brigade.name}

  .row
    .col-4
      %h2 Brigade Leaders

      %ul
      - @brigade.brigade_leaders.each do |l|
        %li= l.name

      %h3 Add New:
      = form_for BrigadeLeader.new(brigade: @brigade), url: add_leader_brigade_path(@brigade) do |f|
        .form-group
          = f.label :name
          = f.text_field :name, class: 'form-control'

        .form-group
          = f.label :email
          = f.text_field :email, type: :email, class: 'form-control'

        .actions
          = f.submit "Add Brigade Leader", class: 'btn btn-primary'

app/views/brigade/show.html.haml
.container
  .row
    .col-12
      %h1= @brigade.name
      - if current_user&.can_manage_brigade?(@brigade)
        = link_to 'Edit', edit_brigade_path(@brigade)

      - if @brigade.brigade_leaders.length
        %strong Brigade Leaders:
        = @brigade.brigade_leaders.map(&:name).join(", ")

      %h2 Members
      - members_over_time = Hash[@stats.find_all { |m| m.metric_name == "meetup_member_count" }.map { |m| [m.created_at.to_date, m.metric_value] }]
      = line_chart members_over_time, min: members_over_time.values.min, max: members_over_time.values.max

      - if @projects.any?
        %h2 Brigade Projects

        - github_projects, non_github_projects = @projects.partition(&:last_pushed_at)
        - active_projects, inactive_projects = github_projects.partition { |p| p.last_pushed_at > 1.year.ago }
        .card-columns
          - active_projects.each do |project|
            - github_repo = project.github_repo
            - github_repo_details = project.github_repo_details

            .card
              .card-header.text-muted
                - if github_repo
                  %i.fas.fa-eye
                  #{github_repo.body['subscribers_count']}

                  %i.fas.fa-star
                  #{github_repo.body['stargazers_count']}
                  - if github_repo.body['fork']
                    %i.fas.fa-code-branch
                    = github_repo.body['parent']['owner']['login']
                    \/
                    = github_repo.body['parent']['name']

              .card-body
                %h5.card-title= project.name
                .card-text
                  = github_repo.body['description']
              .card-footer
                - if project.link_url
                  = link_to project.link_url, target: '_blank' do
                    = project.link_url
                    %i.fas.fa-external-link-alt
                - if project.code_url
                  = link_to project.code_url, target: '_blank' do
                    %i.fab.fa-github

                - if project.last_pushed_at
                  Last updated: #{distance_of_time_in_words_to_now project.last_pushed_at}

        %h2 Inactive Projects:
        %ul
        - inactive_projects.each do |project|
          %li
            %strong= project.name
        - non_github_projects.each do |project|
          %li
            %strong= project.name
            (Unknown Code URL: #{project.code_url})

      - if @meetup_page
        - details = @meetup_page.body

        %h2 Meetup Details
        %ul
          %li
            %strong Last Updated:
            %span{ title: @meetup_page.updated_at }= distance_of_time_in_words_to_now @meetup_page.updated_at
          %li
            %strong Next Event:
            = Time.at(details['next_event'] / 1000) if details['next_event']
          %li
            %strong Last Event:
            = Time.at(details['last_event'] / 1000) if details['last_event']
          %li
            %strong Organizers:
            = details['organizers'].map { |o| o['name'] }.join(', ')
          %li
            %strong Total RSVPs:
            = details['past_rsvps']
          %li
            %strong Repeat RSVPers:
            = details['repeat_rsvpers']
          %li
            %strong Past Events:
            = details['past_events']
          %li
            %strong Member Count:
            = details['member_count']
          %li
            %strong Upcoming Events:
            = details['upcoming_events']

      - else
        %p No Meetup Metrics (#{link_to @brigade.meetup_url, @brigade.meetup_url})