config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
  }

  resources :brigade, only: %i[show edit] do
    post :add_leader, on: :member
  end

  resources :projects, only: %i[index] do
    get 'search', on: :collection
  end

  root to: 'home#show'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Brigade Network
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css", :integrity => "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T", :rel => "stylesheet"}/
    %script{:crossorigin => "anonymous", :integrity => "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo", :src => "https://code.jquery.com/jquery-3.3.1.slim.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"}
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{ src: 'https://kit.fontawesome.com/5cb818d9ff.js', crossorigin: 'anonymous' }

  %body
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light.mb-4
      .container
        = link_to 'Brigade Network', root_path, class: 'navbar-brand'
        %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
          %span.navbar-toggler-icon
        #navbarSupportedContent.collapse.navbar-collapse
          %ul.navbar-nav.mr-auto
            = nav_link_item 'Home', root_path
            = nav_link_item 'Project Search', projects_path
            -#
              %li.nav-item.dropdown
                %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                  Dropdown
                .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
                  %a.dropdown-item{:href => "#"} Action
                  %a.dropdown-item{:href => "#"} Another action
                  .dropdown-divider
                  %a.dropdown-item{:href => "#"} Something else here
              %li.nav-item
                %a.nav-link.disabled{"aria-disabled" => "true", :href => "#", :tabindex => "-1"} Disabled
          %span.navbar-nav
            - if current_user
              .nav-item
                = link_to edit_user_registration_path, class: ['nav-link', ('active' if current_page?(edit_user_registration_path))] do
                  = current_user.email
                  - if current_user.admin?
                    .badge.badge-pill.badge-primary Admin
                  - if current_user.brigade_leaders.any?
                    .badge.badge-pill.badge-secondary Brigade Leader
              .nav-item
                = link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link'
            - else
              .nav-item{ class: ('active' if current_page?(new_user_session_path)) }
                = link_to 'Log In', new_user_session_path, class: 'nav-link'
    - if notice || alert
      - if notice
        %p.alert.alert-info= notice
      - if alert
        %p.alert.alert-warning= alert

    = yield